# Generated by Django 4.1.7 on 2023-02-27 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('plastico_objeto', models.CharField(max_length=255)),
                ('medusas', models.CharField(max_length=255)),
                ('otros', models.CharField(max_length=255)),
                ('plastico_agregados', models.CharField(max_length=255)),
                ('boyas', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='map_viewer.document')),
            ],
        ),
    ]
